name: build paper

on:
  push:
    paths:
      - 'paper/**'
      - 'attrition/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install -e .
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: paper/no-regret-is-not-no-harm.tex
          work_in_root_file_dir: true
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/no-regret-is-not-no-harm.pdf
